version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the application..."
      - npm run build || echo "No build script found, skipping..."

  post_build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'

