version: 0.2
phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build || echo "no build step"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: .
